run_calculator: CPU_Calculator.exe
	CPU_Calculator.exe

CPU_Calculator.exe: CPU_executor.cpp Stack\Stack_functions.cpp Stack\Log_functions.cpp Stack\Stack.h CPU_assembler.cpp CPU.h Commands.h
	g++ CPU_executor.cpp Stack\Stack_functions.cpp Stack\Log_functions.cpp -o CPU_Calculator.exe

run_assembler: CPU_assembler.exe
	CPU_assembler.exe

CPU_assembler.exe: CPU_assembler.cpp Input.txt CPU.h Commands.h
	g++ CPU_assembler.cpp -o CPU_assembler.exe	
 
